version: '3'
services:
  meemo:
    image: qmcgaw/meemo
    container_name: meemo
    volumes:
      - ./users.json:/users.json
      - ./data:/data
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/meemo
      - APP_ORIGIN=http://localhost
    ports:
      - 3000:3000/tcp
    depends_on:
      - mongodb
    networks:
      - backend
    restart: always
  mongodb:
    image: mongo
    container_name: meemo_mongo
    volumes:
      - ./database:/data/db
    networks:
      - backend
    restart: always
    
networks:
  backend:
    driver: bridge
